import "@/styles/globals.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";
// import { Geist } from "next/font/google";

import {ClerkProvider} from '@clerk/nextjs'
import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Mem's PlaniFy | SaaS GitHub AI",
  description: "Generated by KLC Computing",
  icons: [{ rel: "icon", url: "/favicon-32x32.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
